version: 2.1
orbs:
  node: circleci/node@5.1.0
  
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  deploy:
    docker:
      - image: circleci/node@5.0.2
    steps:
      - checkout
      - run:
          name: Deploy Fly
          command: |
            wget -qO- 'https://getfly.fly.dev/linux-x86-64/flyctl.tgz' | tar xz
            ./flyctl deploy -t $FLY_AUTH_TOKEN --build-arg RedisDbUrl=$REDIS_URL --build-arg RedisDbPassword=$REDIS_PASSWORD --build-arg CloudDBConfig=$DB_CONFIG  

workflows:
  sample:
    jobs:
      - build
      - node/test:
          test-results-path: junit.xml
          requires:
            - build
      - deploy:
          requires:
            - build
