/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class QuestionsList {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('id', 'String');
        fieldTypeMap.set('question', 'String');
        fieldTypeMap.set('categoryId', 'String');
        fieldTypeMap.set('isApproved', 'Boolean');
        return fieldTypeMap;
    }

    getClassName() {
        return 'QuestionsList';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        indexList.push('categoryId');
        return indexList;
    }

    getEncryptedFieldList() {
        return [];
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setQuestion(question) {
        this.question = question;
    }

    getQuestion() {
        return this.question;
    }

    setCategoryId(categoryId) {
        this.categoryId = categoryId;
    }

    getCategoryId() {
        return this.categoryId;
    }

    setIsApproved(isApproved) {
        this.isApproved = isApproved;
    }

    getIsApproved() {
        return this.isApproved;
    }
}

module.exports = QuestionsList
